---
# tasks file for apache
- name: Calaculate the package list by concatinate the 2 lists apache_base_packages & apache_optional_packages
  set_fact:
    apache_packages: "{{apache_optional_packages | union(apache_base_packages) }}"
- name: Check that apache_packages is installed 
  yum:
    name: "{{apache_packages}}"
    state: present
# will use the enable_repo defined in the role apaches defaults if not defined omit 
    enable_repo: "{{apache_enable_repo | default(omit,true) }}" 
- name: use the seboolean to allow httpd connections to db     
  seboolean:
    name: httpd_can_network_connect_db
    state: yes
    persistent: yes

