---
- name: This playbook will use the forks directive defined in the ansible.cfg  in order to excute 2 tasks simultaneous at a time 
  hosts: all
  tasks:
  - name: upgrade the bash completion
    yum:
      name: bash 
      state: latest
  - name: create a file called selinux
    file:
      path: /home/ibm/templates/selinuxtest
      mode: 0644
      setype: httpd_config_t
      state: touch 
  - name: Set the selinux context on the file
    sefcontext:
      target: /home/ibm/templates/selinuxtest
      setype: httpd_config_t
