---
- name: play to add groups and add users and create users to that group 
  hosts: all
  vars_files:
    - /rhce/vars/chapter10Example9-users-vars.yml
  tasks:
  - name: This tasks will create groups
    group:
      name: "{{item}}"
      state: present
    loop: 
      - GTS
      - GBS
      - TDC
  - name: Create users and assign them to groups
    user:
      name: "{{item.name}}" 
      groups: "{{item.group}}"
      state: present
      create_home: true
      shell: "{{item.shell}}"
    loop: "{{users}}"  
  - name: allow ibm user to have access to users
    authorized_key:
      user: "{{item.name}}"
      state: present
      key: "{{ lookup('file', '/home/ibm/.ssh/id_rsa.pub') }}" 
    loop: "{{users}}"  
