---
# handlers file for mabdelm.create-users
- name: generate ssh-keys
  user:
    name: "{{item.name}}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    state: absent
- name: restart sshd
  service: 
    name: sshd
    state: restarted  
 
 
