---
- name: This playbook will use the time synchroniztion using ntp server and show that post_taks run after roles
  hosts: '*'
  post_tasks:
  - name: set the timezone to UTC
    timezone:
      name: "{{timezone}}"
  - name:  check the date and time
    command: timedatectl
    register: timedate  
  - name: print the output
    debug:
      var: timedate
  vars:
    timesync_ntp_servers:
      - hostname: 2.rhel.pool.ntp.org
        iburst: yes
    timezone: UTC    
 

